### ISSUE TITLE
Create validation to read operating system environment variables in the `env` field

### ISSUE THREAD

**Issue by isaque-brisa** [isaqueveras/zoity#12]
```yaml
- name: My Backend
  command: 'go run main.go'
  path: ~/go/github.com/username/backend
  ports: [8081]
  env:
    - BACKEND_CONFIG=${BACKEND_CONFIG}
```
