### ISSUE TITLE
Service Configuration File Structure

### ISSUE THREAD

**Issue by isaqueveras** [isaqueveras/zoity#6]
In this topic, I briefly analyze how I am modeling the structure of the configuration file for each service.

**Comment by isaqueveras** [comment]
```yaml
- name: Service 01
  command: ''
  path: ~/go/github.com/username/service01
  env:
    - CONFIG_SERVICE_01=~/config_01.json
    - MAX_OPEN_CONN=10
    - MAX_IDLE_CONN=5

- name: Service 02
  command: ''
  path: ~/go/github.com/username/service02
  env:
    - CONFIG_SERVICE_02=~/config_02.json
    - MAX_OPEN_CONN=10
    - MAX_IDLE_CONN=5
```
